VidTracker/Pages/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra;
using CassandraDataLayer;
using CassandraDataLayer.QueryEntities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace VidTracker.Pages
{
    public class AdminModel : PageModel
    {
        [BindProperty]
        public string Message { get; set; } = "";
        [BindProperty]
        public string Mere { get; set; } = "";
        [BindProperty]
        public Bolnica Bolnica { get; set; }
        [BindProperty]
        public string MessageBolnica { get; set; } = "";
        [BindProperty]
        public Ambulanta Ambulanta { get; set; }
        [BindProperty]
        public string MessageAmbulanta { get; set; } = "";
        [BindProperty]
        public Korisnik Laborant { get; set; }
        [BindProperty]
        public string MessageLaborant { get; set; } = "";
        [BindProperty]
        public Korisnik Bolnicar { get; set; }
        [BindProperty]
        public string MessageBolnicar { get; set; } = "";
        [BindProperty]
        public string UsernameZaBrisanje { get; set; } = "";
        [BindProperty]
        public string MessageBrisanje { get; set; } = "";

        [BindProperty]
        public bool PrikaziGradStatistiku { get; set; } = false;
        [BindProperty]
        public string IzabraniGrad { get; set; } = "";
        [BindProperty]
        public int[] GradStatistika { get; set; } = new int[6];
        [BindProperty(SupportsGet =true)]
        public List<string> Gradovi { get; set; }

        public void OnGet()
        {
            Gradovi = DataProvider.GetAmbulantas().Select(x => x.Grad).Distinct().ToList();
        }

        public IActionResult OnPost()
        {
            Gradovi = DataProvider.GetAmbulantas().Select(x => x.Grad).Distinct().ToList();
            IzracunajStatistiku();
            return Page();
        }
        public IActionResult OnPostGrad()
        {
            Gradovi = DataProvider.GetAmbulantas().Select(x => x.Grad).Distinct().ToList();
            PrikaziGradStatistiku = true;
            var listaAmbulantas = DataProvider.GetAmbulantas();
            GradStatistika = new int[6];
            if (listaAmbulantas != null)
            {
                GradStatistika[0] = listaAmbulantas.Where(x => x.Grad == IzabraniGrad)
                                                    .Sum(x => x.BrojPregledanih);
                GradStatistika[1] = listaAmbulantas.Where(x => x.Grad == IzabraniGrad)
                                                    .Sum(x => x.BrojTestiranih);
                GradStatistika[2] = listaAmbulantas.Where(x => x.Grad == IzabraniGrad)
                                                    .Sum(x => x.BrojPozitivnih);
                GradStatistika[3] = listaAmbulantas.Where(x => x.Grad == IzabraniGrad && x.Dan == LocalDate.Parse(DateTime.Today.AddDays(-1).ToString("yyyy-MM-dd")))
                                                    .Sum(x => x.BrojPregledanih);
                GradStatistika[4] = listaAmbulantas.Where(x => x.Grad == IzabraniGrad && x.Dan == LocalDate.Parse(DateTime.Today.AddDays(-1).ToString("yyyy-MM-dd")))
                                                    .Sum(x => x.BrojTestiranih);
                GradStatistika[5] = listaAmbulantas.Where(x => x.Grad == IzabraniGrad && x.Dan == LocalDate.Parse(DateTime.Today.AddDays(-1).ToString("yyyy-MM-dd")))
                                                    .Sum(x => x.BrojPozitivnih);
            }
            else
            {
            }

            return Page();
        }

        public IActionResult OnPostBolnica()
        {
           
                 Gradovi = DataProvider.GetAmbulantas().Select(x => x.Grad).Distinct().ToList();
                int id= DataProvider.getID("BOLNICA");
            
                DataProvider.AddBolnica(id, Bolnica.Naziv, Bolnica.Adresa, Bolnica.Grad);
                MessageBolnica = "Uspesno kreirana bolnica sa ID-em " + id + "!";
                return Page();
          
        }

        public IActionResult OnPostAmbulanta()
        {
          
            Gradovi = DataProvider.GetAmbulantas().Select(x => x.Grad).Distinct().ToList();
            int id = DataProvider.getID("AMBULANTA");
            DataProvider.AddAmbulanta(id, Ambulanta.Naziv, Ambulanta.Adresa, Ambulanta.Grad,
                                            LocalDate.Parse(DateTime.Today.ToString("yyyy-MM-dd")), 0, 0, 0, 0);
            MessageAmbulanta = "Uspesno kreirana ambulanta sa ID-em " + id + "!";
            return Page();
          
        }

        public IActionResult OnPostBolnicar()
        {
            Gradovi = DataProvider.GetAmbulantas().Select(x => x.Grad).Distinct().ToList();
            var korisnik = DataProvider.GetKorisnik(Bolnicar.Username);
            var radnoMestoBolnica = DataProvider.GetBolnica(Bolnicar.IdRadnogMesta, Bolnicar.Grad);
            if (korisnik.Username != null)
            {
                MessageBolnicar = "Vec postoji korisnik sa tim korisnickim imenom!";
                return null;
            }
            else if (radnoMestoBolnica.BolnicaID == 0)
            {
                MessageBolnicar = "Ne postoji ta bolnica!";
                return null;
            }
            else if (Bolnicar.Password == null)
            {
                MessageLaborant = "Sifra je obavezna!";
                return null;
            }
            else
            {
                DataProvider.AddKorisnik(Bolnicar.Username, Bolnicar.Password, "Bolnicar", Bolnicar.Grad, Bolnicar.IdRadnogMesta);
                MessageBolnicar = "Uspesno kreiran korisnik " + Bolnicar.Username + "!";
                return Page();
            }
        }
        public IActionResult OnPostLaborant()
        {
            Gradovi = DataProvider.GetAmbulantas().Select(x => x.Grad).Distinct().ToList();
            var korisnik = DataProvider.GetKorisnik(Laborant.Username);
            var radnoMestoAmbulanta = DataProvider.GetAmbulanta(Laborant.IdRadnogMesta, Laborant.Grad);
            if (korisnik.Username != null)
            {
                MessageLaborant = "Vec postoji korisnik sa tim korisnickim imenom!";
                return null;
            }
            else if (radnoMestoAmbulanta.Ambulanta_id == 0)
            {
                MessageLaborant = "Ne postoji ta ambulanta!";
                return null;
            }
            else if (Laborant.Password == null)
            {
                MessageLaborant = "Sifra je obavezna!";
                return null;
            }
            else
            {
                DataProvider.AddKorisnik(Laborant.Username, Laborant.Password, "Laborant", Laborant.Grad, Laborant.IdRadnogMesta);
                MessageLaborant = "Uspesno kreiran korisnik " + Laborant.Username + "!";
                return Page();
            }
        }
        public IActionResult OnPostObrisi()
        {
            Gradovi = DataProvider.GetAmbulantas().Select(x => x.Grad).Distinct().ToList();
            var korisnik = DataProvider.GetKorisnik(UsernameZaBrisanje);
            if (korisnik.Username != null)
            {
                DataProvider.DeleteKorisnik(UsernameZaBrisanje);
                if (korisnik.Rola_Id == "Bolnicar")
                {
                    MessageBrisanje = "Obrisan bolnicar " + UsernameZaBrisanje;
                }
                else if (korisnik.Rola_Id == "Laborant")
                {
                    MessageBrisanje = "Obrisan laborant " + UsernameZaBrisanje;
                }
                return null;
            }
            else
            {
                MessageBrisanje = "Ne postoji korisnik sa tim korisnickim imenom";
                return Page();
            }
        }


        public void IzracunajStatistiku()
        {
            var listaAmbulantas = DataProvider.GetAmbulantas();
            var statistika = DataProvider.GetStatistika(LocalDate.Parse(DateTime.Today.ToString("yyyy-MM-dd")));
            if (statistika.Dan.Equals(new Cassandra.LocalDate(1960, 1, 1)))
            {
                var brojTestiranih = listaAmbulantas.Where(x => x.Dan == LocalDate.Parse(DateTime.Today.AddDays(-1).ToString("yyyy-MM-dd")))
                                                    .Sum(x => x.BrojTestiranih);
                var brojPregledanih = listaAmbulantas.Where(x => x.Dan == LocalDate.Parse(DateTime.Today.AddDays(-1).ToString("yyyy-MM-dd")))
                                                    .Sum(x => x.BrojPregledanih);
                var brojPozitivnih = listaAmbulantas.Where(x => x.Dan == LocalDate.Parse(DateTime.Today.AddDays(-1).ToString("yyyy-MM-dd")))
                                                    .Sum(x => x.BrojPozitivnih);
                DataProvider.AddStatistika(LocalDate.Parse(DateTime.Today.ToString("yyyy-MM-dd")), Mere, brojTestiranih, brojPregledanih, brojPozitivnih);
                Message = "Uspesno izracunata statistika!";
            }
            else
            {
                Message = "Danas vec izracunata statistika!";
            }
        }
    }
}

VidTracker/Pages/Ambulanta.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra;
using CassandraDataLayer;
using CassandraDataLayer.QueryEntities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace VidTracker.Pages
{
    public class AmbulantaModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public Ambulanta Ambulanta { get; set; }
        [BindProperty]
        public string ErrorMessage { get; set; } = "";
        [BindProperty]
        public string SuccessMessage { get; set; } = "";
        [BindProperty]
        public int BrojZdravstvene { get; set; }
        [BindProperty]
        public bool Pozitivan { get; set; }
        [BindProperty]
        public string Ime { get; set; }
        [BindProperty]
        public string Prezime { get; set; }
        [BindProperty]
        public int Godine { get; set; }
        [BindProperty]
        public DateTime Dan { get; set; }
        public SelectList ListaDana { get; set; }
        [BindProperty]
        public string IzabranDan { get; set; }
        [BindProperty]
        public int BrojTestiranih { get; set; }
        [BindProperty]
        public int BrojPregledanih { get; set; }
        [BindProperty]
        public int BrojPozitivnih { get; set; }
        [BindProperty]
        public int BrojLekara { get; set; }
        [BindProperty]
        public string KorisnickoIme { get; set; }
        [BindProperty]
        public string Sifra { get; set; }
        [BindProperty]
        public string ErrorMessageZaRacunanje { get; set; } = "";
        [BindProperty]
        public int BrojPregledanihZaDanas { get; set; }
        [BindProperty]
        public int BrojLekaraZaDanas { get; set; }


        public void OnGet(string grad, int radno_mesto)
        {
            Ambulanta = DataProvider.GetAmbulanta(radno_mesto, grad);
            ListaDana = new SelectList(DataProvider.GetAmbulantaDani(radno_mesto, grad));
            Dan = new DateTime(Ambulanta.Dan.Year, Ambulanta.Dan.Month, Ambulanta.Dan.Day);
            BrojPozitivnih = Ambulanta.BrojPozitivnih;
            BrojPregledanih = Ambulanta.BrojPregledanih;
            BrojTestiranih = Ambulanta.BrojTestiranih;
            BrojLekara = Ambulanta.BrojLekara;
        }

        public IActionResult OnPostPacijent(int id, string grad, DateTime dan)
        {
            LocalDate datum = new LocalDate(dan.Year, dan.Month, dan.Day);
            Ambulanta = DataProvider.GetAmbulantaPoDanu(id, grad, datum);
            BrojPozitivnih = Ambulanta.BrojPozitivnih;
            BrojPregledanih = Ambulanta.BrojPregledanih;
            BrojTestiranih = Ambulanta.BrojTestiranih;
            BrojLekara = Ambulanta.BrojLekara;
            ListaDana = new SelectList(DataProvider.GetAmbulantaDani(id, grad));
            Dan = dan;

            if (BrojZdravstvene == 0)
            {
                ErrorMessage = "* Oznacava obavezna polja";
                return Page();
            }
            else
            {
                DateTimeOffset vreme = DateTimeOffset.Now;
                DataProvider.AddPacijent(BrojZdravstvene, Ime, Prezime, Godine, Pozitivan, vreme);
                DataProvider.AddAmbulantaTestovi(Ambulanta.Ambulanta_id, Ambulanta.Grad, vreme, Pozitivan);
                SuccessMessage = "Uspesno dodat test!";
                return Page();
            }
        }

        public IActionResult OnPostOsvezi()
        {
            if (!string.IsNullOrEmpty(IzabranDan))
            {
                string[] splitString = IzabranDan.Split('/');

                LocalDate datum = new LocalDate(Int32.Parse(splitString[2]), Int32.Parse(splitString[1]), Int32.Parse(splitString[0]));
                Ambulanta = DataProvider.GetAmbulantaPoDanu(Ambulanta.Ambulanta_id, Ambulanta.Grad, datum);
                ListaDana = new SelectList(DataProvider.GetAmbulantaDani(Ambulanta.Ambulanta_id, Ambulanta.Grad));
                Dan = new DateTime(Ambulanta.Dan.Year, Ambulanta.Dan.Month, Ambulanta.Dan.Day);
                BrojPozitivnih = Ambulanta.BrojPozitivnih;
                BrojPregledanih = Ambulanta.BrojPregledanih;
                BrojTestiranih = Ambulanta.BrojTestiranih;
                BrojLekara = Ambulanta.BrojLekara;
            }
            return Page();
        }

        public IActionResult OnPostIzracunaj(int id, string grad, DateTime dan)
        {
            LocalDate datum = new LocalDate(dan.Year, dan.Month, dan.Day);
            Ambulanta = DataProvider.GetAmbulantaPoDanu(id, grad, datum);
            BrojPozitivnih = Ambulanta.BrojPozitivnih;
            BrojPregledanih = Ambulanta.BrojPregledanih;
            BrojTestiranih = Ambulanta.BrojTestiranih;
            BrojLekara = Ambulanta.BrojLekara;
            ListaDana = new SelectList(DataProvider.GetAmbulantaDani(id, grad));
            Dan = dan;
            if (string.IsNullOrEmpty(KorisnickoIme))
            {
                ErrorMessageZaRacunanje = "Molimo Vas unesite korisnicko ime";
                return Page();
            }
            if (string.IsNullOrEmpty(Sifra))
            {
                ErrorMessageZaRacunanje = "Molimo Vas unesite sifru";
                return Page();
            }
            Korisnik korisnik = DataProvider.GetKorisnik(KorisnickoIme);
            if (korisnik == null)
            {
                ErrorMessageZaRacunanje = "Ne postoji ovaj korisnik u bazi";
                return Page();
            }
            if (korisnik.Password != Sifra)
            {
                ErrorMessageZaRacunanje = "Pogresna lozinka";
                return Page();
            }
            if (korisnik.IdRadnogMesta != Ambulanta.Ambulanta_id || korisnik.Grad != Ambulanta.Grad)
            {
                ErrorMessageZaRacunanje = "Unet korisnik ne radi u ovoj ambulanti";
                return Page();
            }

            DateTime datumDateTime = DateTime.Now;
            LocalDate danas = new LocalDate(datumDateTime.Year, datumDateTime.Month, datumDateTime.Day);
            Ambulanta ambulantaDanas = DataProvider.GetAmbulantaPoDanu(korisnik.IdRadnogMesta, korisnik.Grad, danas);

            if (ambulantaDanas.Ambulanta_id != 0)
            {
                ErrorMessageZaRacunanje = "Za danas je vec izracunata statistika";
                return Page();
            }

            Ambulanta ambulantaZaUnos = DataProvider.GetAmbulanta(korisnik.IdRadnogMesta, korisnik.Grad);

            List<AmbulantaTestovi> testovi = DataProvider.GetAmbulantaTestoviZaDanas(ambulantaZaUnos.Ambulanta_id, ambulantaZaUnos.Grad, danas);

            int brojTestiranih = 0;
            int brojPozitivnih = 0;

            foreach (AmbulantaTestovi test in testovi)
            {
                if (test.Pozitivan == true)
                    brojPozitivnih++;
                brojTestiranih++;
            }

            DataProvider.AddAmbulanta(korisnik.IdRadnogMesta, ambulantaZaUnos.Naziv, ambulantaZaUnos.Adresa,
                                      ambulantaZaUnos.Grad, danas, brojTestiranih, BrojPregledanihZaDanas,
                                      BrojLekaraZaDanas, brojPozitivnih);

            return RedirectToPage($"/Ambulanta", new { grad = korisnik.Grad, radno_mesto = korisnik.IdRadnogMesta });

        }

    }
}

VidTracker/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace VidTracker.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

VidTracker/Pages/Admin.cshtml
@page
@model VidTracker.Pages.AdminModel
@{

}

<form method="post">
    <input type="text" class="form-control mr-1 mb-2" placeholder="Nove mere" asp-for="@Model.Mere" />
    <button class="btn btn-primary" asp-page-handler="">Dodaj statistiku</button>
    <label class="ml-2">@Model.Message</label>
</form>

<div class="row mt-4">
    <div class="col-6" style="border:1px solid gainsboro;">
        <h1 class="mt-2">Statistika po gradu</h1>
        <form method="post">
            <select class="col-7 mb-1" asp-for="@Model.IzabraniGrad">
                <option value="" disabled selected>Izaberi grad</option>
                @foreach (var grad in Model.Gradovi)
                {
                    <option value="@grad">@grad</option>
                }
            </select>
            <button class="col-4 btn btn-danger mb-1" asp-page-handler="grad">Prikazi statistiku</button>
            @if (Model.PrikaziGradStatistiku)
            {
                <label class="col-7" style="font-weight:bold">Grad:</label>
                <label class="col-3">@Model.IzabraniGrad</label>
                <label class="col-7" style="font-weight:bold">Ukupan broj pregledanih:</label>
                <label class="col-3">@Model.GradStatistika[0]</label>
                <label class="col-7" style="font-weight:bold">Ukupan broj testiranih:</label>
                <label class="col-3">@Model.GradStatistika[1]</label>
                <label class="col-7" style="font-weight:bold">Ukupan broj pozitivnih:</label>
                <label class="col-3">@Model.GradStatistika[2]</label>
                <label class="col-7" style="font-weight:bold">Broj pregledanih prethodnog dana:</label>
                <label class="col-3">@Model.GradStatistika[3]</label>
                <label class="col-7" style="font-weight:bold">Broj testiranih prethodnog dana:</label>
                <label class="col-3">@Model.GradStatistika[4]</label>
                <label class="col-7 mb-1" style="font-weight:bold">Broj pozitivnih prethodnog dana:</label>
                <label class="col-3 mb-1">@Model.GradStatistika[5]</label>
            }
        </form>
    </div>

</div>

<div class="row mt-4">
    <div class="col-6" style="border:1px solid gainsboro;">
        <h1 class="mt-2">Dodaj novu bolnicu</h1>
        <form method="post">
           
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Naziv" asp-for="@Model.Bolnica.Naziv" />
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Grad" asp-for="@Model.Bolnica.Grad" />
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Adresa" asp-for="@Model.Bolnica.Adresa" />
            <button class="btn btn-success mt-2 mb-2" asp-page-handler="bolnica">Dodaj bolnicu</button>
            <label class="ml-2">@Model.MessageBolnica</label>
        </form>
    </div>
    <div class="col-6" style="border:1px solid gainsboro;">
        <h1 class="mt-2">Dodaj novu ambulantu</h1>
        <form method="post">
          
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Naziv" asp-for="@Model.Ambulanta.Naziv" />
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Grad" asp-for="@Model.Ambulanta.Grad" />
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Adresa" asp-for="@Model.Ambulanta.Adresa" />
            <button class="btn btn-success mt-2 mb-2" asp-page-handler="ambulanta">Dodaj ambulantu</button>
            <label class="ml-2">@Model.MessageAmbulanta</label>
        </form>
    </div>
</div>

<div class="row mt-4">
    <div class="col-6" style="border:1px solid gainsboro;">
        <h1 class="mt-2">Dodaj novog bolnicara</h1>
        <form method="post">
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Username" asp-for="@Model.Bolnicar.Username" />
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Password" asp-for="@Model.Bolnicar.Password" />
            <input type="number" class="form-control mt-2 ml-1 mr-1" placeholder="ID radnog mesta" min="1" asp-for="@Model.Bolnicar.IdRadnogMesta" />
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Grad" asp-for="@Model.Bolnicar.Grad" />
            <button class="btn btn-danger mt-2 mb-2" asp-page-handler="bolnicar">Dodaj bolnicara</button>
            <label class="ml-2">@Model.MessageBolnicar</label>
        </form>
    </div>
    <div class="col-6" style="border:1px solid gainsboro;">
        <h1 class="mt-2">Dodaj novog laboranta</h1>
        <form method="post">
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Username" asp-for="@Model.Laborant.Username" />
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Password" asp-for="@Model.Laborant.Password" />
            <input type="number" class="form-control mt-2 ml-1 mr-1" placeholder="ID radnog mesta" min="1" asp-for="@Model.Laborant.IdRadnogMesta" />
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Grad" asp-for="@Model.Laborant.Grad" />
            <button class="btn btn-danger mt-2 mb-2" asp-page-handler="laborant">Dodaj laboranta</button>
            <label class="ml-2">@Model.MessageLaborant</label>
        </form>
    </div>
</div>

<div class="row mt-4">
    <div class="col-6" style="border:1px solid gainsboro;">
        <h1 class="mt-2">Obrisi bolnicara/laboranta</h1>
        <form method="post">
            <input type="text" class="form-control mt-2 ml-1 mr-1" placeholder="Username" asp-for="@Model.UsernameZaBrisanje" />
            <button class="btn btn-danger mt-2 mb-2" asp-page-handler="obrisi">Obrisi</button>
            <label class="ml-2">@Model.MessageBrisanje</label>
        </form>
    </div>
</div>

VidTracker/Pages/Ambulanta.cshtml
@page
@model VidTracker.Pages.AmbulantaModel
@{
}
@*<p class="lead">
        @Model.Ambulanta.Grad, @Model.Ambulanta.Adresa @Model.Ambulanta.Naziv
    </p>*@
<h2 class="mb-3">
    @Model.Ambulanta.Grad, @Model.Ambulanta.Adresa - @Model.Ambulanta.Naziv
</h2>

<hr />

<div class="row">
    <div class="col-6">
        <label class="text-danger">@Model.ErrorMessage</label>
        <label class="text-success">@Model.SuccessMessage</label>
        <form class="form-group" method="post">
            <input type="hidden" asp-for="Ambulanta.Grad" />
            <input type="hidden" asp-for="Ambulanta.Ambulanta_id" />
            <input type="hidden" asp-for="Ambulanta.Naziv" />
            <div class="form-inline mb-2">
                <label class="mr-4">Broj zdravstvene knjizice *</label>
                <input class="form-control" asp-for="BrojZdravstvene">
            </div>
            <div class="form-inline mb-2">
                <input placeholder="Ime" class="form-control mr-2" asp-for="Ime">
                <input placeholder="Prezime" class="form-control" asp-for="Prezime">
            </div>
            <div class="form-inline mb-2">
                <label>Godine</label>
                <input placeholder="Godine" class="form-control ml-2" asp-for="Godine">
            </div>
            <div class="form-check mb-2 mr-2">
                <input class="form-check-input" asp-for="Pozitivan">
                <label class="form-check-label"> Pozitivan</label>
            </div>
            <button type="submit" asp-route-dan="@Model.Ambulanta.Dan" asp-route-id="@Model.Ambulanta.Ambulanta_id" asp-route-grad="@Model.Ambulanta.Grad" class="btn-sm btn-primary" asp-page-handler="pacijent">Dodaj testiranje u bazu</button>
        </form>
    </div>
    <div class="col-6">
        <form method="post">
            <input type="hidden" asp-for="Ambulanta.Grad" />
            <input type="hidden" asp-for="Ambulanta.Ambulanta_id" />
            <h2>Podaci za @Model.Dan.Day/@Model.Dan.Month/@Model.Dan.Year</h2>
            <div>
                <label>Broj testiranih: @Model.BrojTestiranih</label>
            </div>
            <div>
                <label>Broj pozitivnih: @Model.BrojPozitivnih</label>
            </div>
            <div>
                <label>Broj pregledanih: @Model.BrojPregledanih</label>
            </div>
            <div class="mb-2">
                <label>Broj lekara: @Model.BrojLekara</label>
            </div>
            <select asp-for="IzabranDan" asp-items="Model.ListaDana"></select>
            <button type="submit" class="btn-sm btn-primary ml-2" asp-page-handler="osvezi">Osvezi podatke</button>
        </form>
        <hr />
        <h4>Izracunaj danasnje podatke</h4>
        <label class="text-danger">@Model.ErrorMessageZaRacunanje</label>
        <form class="form-inline" method="post">
            <input type="hidden" asp-for="Ambulanta.Grad" />
            <input type="hidden" asp-for="Ambulanta.Ambulanta_id" />
            <div class="form-inline">
                <div class="form-group mb-2 mr-2">
                    <label class="mr-1 mb-1">Broj lekara za danas</label>
                    <input class="form-control" placeholder="Korisnicko ime" asp-for="BrojLekaraZaDanas">
                </div>
                <div class="form-group  mb-2 mr-2">
                    <label class="mr-1">Broj pregledanih pacijenata za danas</label>
                    <input class="form-control" placeholder="Sifra" asp-for="BrojPregledanihZaDanas">
                </div>
            </div>
            <div class="form-group mb-2 mr-2">
                <input type="text" class="form-control" placeholder="Korisnicko ime" asp-for="KorisnickoIme">
            </div>
            <div class="form-group  mb-2 mr-2">
                <input type="password" class="form-control" placeholder="Sifra" asp-for="Sifra">
            </div>
            <button type="submit" asp-route-dan="@Model.Ambulanta.Dan" asp-route-id="@Model.Ambulanta.Ambulanta_id" asp-route-grad="@Model.Ambulanta.Grad" class="btn btn-primary mb-2" asp-page-handler="Izracunaj">Potvrdi</button>
        </form>
    </div>
</div>